import type {Metadata} from "next";
import "@app/globals.css";

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
    return children
}

export const metadata: Metadata = {
    title: "YOU DIN TV",
    description: "Generated by XIAO-DIN",
};
